Models/User.cs
namespace PawPok.Models;

public class User
{
    public int Id { get; set; }
    public string? Username { get; set; }
    public string? Password { get; set; }
    public string? ProfilePictureURL { get; set; } = "/images/default-pfp.jpg";
    public string? Name { get; set; }
    public string? Bio { get; set; } = string.Empty;
    public ICollection<Follow> Following { get; set; } = default!;
    public ICollection<Follow> Followers { get; set; } = default!;
    public ICollection<Video> Videos { get; set; } = default!;

    public User() { }

    public User(string username, string password)
    {
        Username = username;
        Password = password;
        Name = username;
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PawPok.Data;
using PawPok.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Routing.Constraints;

namespace PawPok.Controllers;

public class UserController : Controller
{
    private readonly DataContext _context;

    public UserController(DataContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        if (User!.Identity!.IsAuthenticated)
            return RedirectToAction("Profile", new { username = User.Identity.Name });

        return RedirectToAction("Login", "Authentication");
    }

    public IActionResult Profile(string username)
    {
        User? user = _context.Users.FirstOrDefault(u => u.Username == username);

        if (user == null)
            return NotFound();

        ViewBag.following = _context.Follows.Where(f => f.FollowerId == user.Id).Count();
        ViewBag.followers = _context.Follows.Where(f => f.FollowingId == user.Id).Count();

        user.Videos = _context.Videos.Where(v => v.UserId == user.Id).Include(v => v.Likes).OrderByDescending(v => v.UploadDate).ToList();

        ViewBag.likes = user.Videos.Sum(v => v.Likes.Count());

        if (User!.Identity!.IsAuthenticated)
        {
            int myId = _context.Users.FirstOrDefault(u => u.Username == User!.Identity!.Name)!.Id;

            ViewBag.isFollowed = _context.Follows.Any(f => f.FollowerId == myId && f.FollowingId == user.Id);
        }
        else
            ViewBag.isFollowed = false;

        return View(user);
    }

    public IActionResult Follow(int userId)
    {
        if (User!.Identity!.IsAuthenticated == false)
            return RedirectToAction("Login", "Authentication");

        User? other = _context.Users.FirstOrDefault(u => u.Id == userId);

        if (other == null)
            return NoContent();

        User me = _context.Users.FirstOrDefault(u => u.Username == User!.Identity!.Name)!;

        if (me.Id == other.Id)
            return NoContent();

        Follow? follow = _context.Follows.FirstOrDefault(f => f.FollowerId == me.Id && f.FollowingId == other.Id);

        if (follow != null)
            return NoContent();

        follow = new Follow()
        {
            FollowerId = me.Id,
            FollowingId = other.Id
        };

        try
        {
            _context.Follows.Add(follow);
            _context.SaveChanges();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Unable to follow: " + ex.Message);
        }

        return NoContent();
    }

    public IActionResult Unfollow(int userId)
    {
        if (User!.Identity!.IsAuthenticated == false)
            return RedirectToAction("Login", "Authentication");

        User? other = _context.Users.FirstOrDefault(u => u.Id == userId);

        if (other == null)
            return NoContent();

        User me = _context.Users.FirstOrDefault(u => u.Username == User!.Identity!.Name)!;

        if (me.Id == other.Id)
            return NoContent();

        Follow? follow = _context.Follows.FirstOrDefault(f => f.FollowerId == me.Id && f.FollowingId == other.Id);

        if (follow == null)
            return NoContent();

        try
        {
            _context.Follows.Remove(follow);
            _context.SaveChanges();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Unable to unfollow: " + ex.Message);
        }

        return NoContent();
    }


    [HttpPost]
    public async Task<IActionResult> Edit(User user, IFormFile file)
    {
        try
        {
            if (user.Bio == null)
                user.Bio = string.Empty;

            if (string.IsNullOrWhiteSpace(user.Username))
                ModelState.AddModelError(string.Empty, "Username is empty");
            else if (string.IsNullOrWhiteSpace(user.Name))
                ModelState.AddModelError(string.Empty, "Name is empty");
            else if (_context.Users.Any(u => u.Username == user.Username && user.Username != User!.Identity!.Name))
                ModelState.AddModelError(string.Empty, "Username is already taken");
            else if (user.Bio!.Count() > 80)
                return View(user);
            else
            {
                try
                {
                    User me = _context.Users.FirstOrDefault(u => u.Username == User!.Identity!.Name)!;
                    me.Username = user.Username;
                    me.Name = user.Name;
                    me.Bio = user.Bio;

                    if (file != null && file.Length > 0)
                    {
                        if (!string.IsNullOrEmpty(me.ProfilePictureURL) && me.ProfilePictureURL != "/images/default-pfp.jpg")
                        {
                            string old_path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", me.ProfilePictureURL.TrimStart('/'));

                            if (System.IO.File.Exists(old_path))
                                System.IO.File.Delete(old_path);
                        }

                        string extension = Path.GetExtension(file.FileName).ToLowerInvariant();
                        string filename = $"{me.Id}_{DateTimeOffset.UtcNow.ToUnixTimeSeconds()}{extension}";
                        string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", filename);

                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            await file.CopyToAsync(stream);
                        }

                        me.ProfilePictureURL = "/images/" + filename;
                    }

                    _context.SaveChanges();

                    await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

                    List<Claim> claims = new List<Claim>
                        {
                            new Claim(ClaimTypes.Name, me.Username),
                            new Claim("pfp", me.ProfilePictureURL!)
                        };

                    var claimIdentity = new ClaimsIdentity(claims, "AuthenticationCookie");

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimIdentity));

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, "Error saving changes: " + ex.Message);
                }
            }
        }
        catch (Exception ex)
        {
            ModelState.AddModelError(string.Empty, ex.Message);
        }

        return View(user);
    }

    [HttpGet]
    public IActionResult Edit()
    {
        if (User!.Identity!.IsAuthenticated == false)
            return RedirectToAction("Login", "Authentication");

        User user = _context.Users.FirstOrDefault(u => u.Username == User!.Identity!.Name)!;

        return View(user);
    }

    [HttpPost]
    public async Task<IActionResult> Upload(Video video, IFormFile file)
    {
        if (video.Description == null)
            video.Description = string.Empty;

        if (file == null || file.Length == 0)
            ModelState.AddModelError(string.Empty, "No video uploaded");
        else if (video.Description.Count() > 2000)
            ModelState.AddModelError(string.Empty, "Description is too long");
        else
        {
            try
            {
                video.UploadDate = DateTime.Now;
                video.UserId = _context.Users.FirstOrDefault(u => u.Username == User!.Identity!.Name)!.Id;

                _context.Videos.Add(video);
                _context.SaveChanges();

                string filename = $"{video.Id}.mp4";
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "videos", filename);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }

                video.VideoURL = "/videos/" + filename;

                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
        }

        return View(video);
    }

    [HttpGet]
    public IActionResult Upload()
    {
        if (User!.Identity!.IsAuthenticated == false)
            return RedirectToAction("Login", "Authentication");

        Video video = new Video();

        return View(video);
    }

    public IActionResult Like(int videoId)
    {
        if (User!.Identity!.IsAuthenticated == false)
            return RedirectToAction("Login", "Authentication");

        Video? other = _context.Videos.FirstOrDefault(u => u.Id == videoId);

        if (other == null)
            return NoContent();

        User me = _context.Users.FirstOrDefault(u => u.Username == User!.Identity!.Name)!;

        if (me.Id == other.Id)
            return NoContent();

        Like? like = _context.Likes.FirstOrDefault(f => f.UserId == me.Id && f.VideoId == other.Id);

        if (like != null)
            return NoContent();

        like = new Like()
        {
            UserId = me.Id,
            VideoId = other.Id
        };

        try
        {
            _context.Likes.Add(like);
            _context.SaveChanges();
        }
        catch (Exception ex)
        {
            Console.WriteLine("Unable to like: " + ex.Message);
        }

        return NoContent();
    }

    public IActionResult Unlike(int videoId)
    {
        if (User!.Identity!.IsAuthenticated == false)
            return RedirectToAction("Login", "Authentication");

Controllers/VideoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PawPok.Data;
using PawPok.Models;

namespace PawPok.Controllers;

public class VideoController : Controller
{
    private readonly DataContext _context;

    public VideoController(DataContext context)
    {
        _context = context;
    }

    [HttpGet]
    public IActionResult Index(int videoId)
    {
        Video? video = _context.Videos.Include(v => v.Comments).Include(v => v.Likes).Include(v => v.User).FirstOrDefault(v => v.Id == videoId);

        if(video == null)
            return RedirectToAction("Index", "Home");

        video.Comments = video.Comments.OrderByDescending(c => c.CreatedDate).ToList();

        ViewBag.Video = video;

        foreach (var com in video.Comments)
            com.User = _context.Users.FirstOrDefault(u => u.Id == com.UserId);

        Comment comm = new Comment();

        if (User!.Identity!.IsAuthenticated)
        {
            User user = _context.Users.FirstOrDefault(u => u.Username == User!.Identity!.Name)!;

            ViewBag.isFollowed = _context.Follows.Any(f => f.FollowerId == user.Id && f.FollowingId == video.UserId);
            ViewBag.isLiked = _context.Likes.Any(l => l.UserId == user.Id && l.VideoId == video.Id);

            comm.UserId = user.Id;
            comm.VideoId = video!.Id;
        }
        else
        {
            ViewBag.isFollowed = false;
            ViewBag.isLiked = false;
        }

        return View(comm);
    }

    public IActionResult Remove(int videoId)
    {
        if (User!.Identity!.IsAuthenticated)
        {
            Video? video = _context.Videos.Include(v => v.Likes).Include(v => v.Comments).Include(v => v.User).FirstOrDefault(v => v.Id == videoId);

            if (video != null && video.User?.Username == User!.Identity!.Name)
            {
                try
                {
                    string? url = video.VideoURL;

                    _context.Likes.RemoveRange(video.Likes);
                    _context.Comments.RemoveRange(video.Comments);
                    _context.Videos.Remove(video);
                    _context.SaveChanges();

                    if (url != null)
                    {
                        string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", url.TrimStart('/'));

                        if (System.IO.File.Exists(path))
                            System.IO.File.Delete(path);
                    }

                    return RedirectToAction("Profile", "User", new { username = User!.Identity!.Name });
                }
                catch (Exception)
                {

                }
            }
        }

        return NoContent();
    }

    public IActionResult RemoveComment(int commId)
    {
        if (User!.Identity!.IsAuthenticated)
        {
            int myId = _context.Users.FirstOrDefault(u => u.Username == User!.Identity!.Name)!.Id;

            Comment? comm = _context.Comments.Include(c => c.Video).FirstOrDefault(c => c.Id == commId);

            if (comm != null && (comm.UserId == myId || comm.Video?.UserId == myId))
            {
                try
                {
                    int videoId = comm.VideoId;

                    _context.Remove(comm);
                    _context.SaveChanges();

                    return RedirectToAction("Index", new { videoId = videoId });
                }
                catch (Exception)
                {

                }
            }
        }

        return NoContent();
    }
}

Views/User/Edit.cshtml
@model PawPok.Models.User
@{
    ViewData["Title"] = "Edit";
}

<div class="container">
    <h1 class="text-center" style="margin-bottom: 40px">Edit profile</h1>
    <div class="row">
        <div class="mx-auto" style="width: 400px">
            <form id="account" asp-controller="User" asp-action="Edit" method="post" enctype="multipart/form-data">

                <div style="display: flex; flex-direction: row; align-items: center">
                    <input type="hidden" asp-for="ProfilePictureURL" />
                    <div id="pfp" class="pfp" style="background-image: url('@(Url.Content(Model.ProfilePictureURL))')"></div>

                    <button type="button" class="follow-btn" style="margin-left: 20px" onclick="document.getElementById('browse-file').click()">Change</button>
                    <input id="browse-file" type="file" name="file" style="display: none" accept=".png, .jpg, .jpeg" onchange="change_pfp(event)" />

                </div>

                <div class="form-group" style="margin-top: 20px">
                    <label asp-for="Username" class="control-label mb-2">Username</label>
                    <input asp-for="Username" class="form-control" value="@Model.Username" spellcheck="false"/>
                </div>

                <div class="form-group" style="margin-top: 20px">
                    <label asp-for="Name" class="control-label mb-2">Name</label>
                    <input asp-for="Name" class="form-control" value="@Model.Name" spellcheck="false" />
                </div>

                <div class="form-group" style="margin-top: 20px">
                    <label asp-for="Bio" class="control-label mb-2">Bio</label>
                    <textarea id="bio-area" asp-for="Bio" class="form-control mb-2" style="height: 120px; resize: none" spellcheck="false" placeholder="Bio" oninput="update_bio_length()" />@Model.Bio</textarea>
                    <span id="bio-length">0 / 80</span>
                </div>

                @if (ViewData.ModelState[string.Empty] != null)
                {
                    <div class="error-summary" style="margin-top: 20px">
                        @foreach (var error in ViewData.ModelState[string.Empty]!.Errors)
                        {
                            <div class="error-item text-danger">
                                @error.ErrorMessage
                            </div>
                        }
                    </div>
                }

                <div style="margin-top: 20px">
                    <a href="@Url.Action("Index")" class="follow-btn" style="margin-right: 10px">Cancel</a>
                    <button type="submit" class="follow-btn">Save</button>
                </div>

                <div style="margin-top: 60px">
                    <a href="@Url.Action("Remove")" class="follow-btn danger">Delete account</a>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    function update_bio_length() {
        var bio_area = document.getElementById('bio-area');
        var bio_length = document.getElementById('bio-length');

        bio_length.innerText = bio_area.value.length + ' / 80';

        if (bio_area.value.length > 80)
            bio_length.style.color = 'var(--bs-danger)';
        else
            bio_length.style.color = '#eee';
    }

    document.addEventListener('DOMContentLoaded', function () {
        update_bio_length();
    });

    function change_pfp(event) {
        var input = event.target;
        var filename = input.value.split('\\').pop();

        if (!is_valid_extension(filename)) {
            input.value = '';
            document.getElementById('pfp').style.backgroundImage = "url('@(Url.Content(Model.ProfilePictureURL))')"
        }

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                document.getElementById('pfp').style.backgroundImage = 'url(' + e.target.result + ')';
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    function is_valid_extension(filename) {
        var valid = ['png', 'jpg', 'jpeg'];
        var extension = filename.split('.').pop().toLowerCase();
        return valid.includes(extension);
    }
</script>

Views/User/Profile.cshtml
@model PawPok.Models.User
@{
    ViewData["Title"] = Model.Username;
}

<div style="display: flex; flex-direction: column;">
    <div style="display: flex; flex-direction: column">
        <div style="display: flex; flex-direction: row">

            <div class="pfp" style="background-image: url('@Url.Content(Model.ProfilePictureURL)'); margin-right: 20px"></div>

            <div style="display: flex; flex-direction: column">
                <a href style="font-size: 30px; font-weight: 700">@Model.Username</a>
                <span>@Model.Name</span>
                <div>
                    @if (User!.Identity!.Name == Model.Username)
                    {
                        <a href="@Url.Action("Edit")" class="follow-btn mt-2" style="width: 120px">Edit profile</a>
                    }
                    else
                    {
                        <a id="follow-button" href="@Url.Action("Follow", "User", new {userId = Model.Id})" class="follow-btn mt-2" style="display: @(ViewBag.isFollowed ? "none" : "block")">Follow</a>
                        <a id="unfollow-button" href="@Url.Action("Unfollow", "User", new {userId = Model.Id})" class="unfollow-btn mt-2" style="display: @(ViewBag.isFollowed ? "block" : "none")">Followed</a>
                    }
                </div>
            </div>
        </div>
        <div style="display: flex; flex-direction: row; margin-top: 20px">
            <div style="margin-right: 20px">
                <strong>@ViewBag.following</strong>
                <span>Following</span>
            </div>
            <div style="margin-right: 20px">
                <strong>@ViewBag.followers</strong>
                <span>Followers</span>
            </div>
            <div>
                <strong>@ViewBag.likes</strong>
                <span>Likes</span>
            </div>
        </div>
        <div style="margin-top: 20px">
            @if (string.IsNullOrWhiteSpace(Model.Bio))
            {
                <pre>No bio yet.</pre>
            }
            else
            {
                <pre>@Model.Bio</pre>
            }
        </div>
        <div style="margin-top: 20px; display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 24px 16px">
            @foreach (var video in Model.Videos)
            {
                <div>
                    <a href="@Url.Action("Index", "Video", new {videoId = video.Id})">
                        <div style="width: 200px; height: 360px; border-radius: 10px; border: 1px solid #303030; overflow: hidden; display: flex; justify-content: center">
                            <video muted loop class="video-item" style="height: 100%">
                                <source src="@Url.Content(video.VideoURL)" type="video/mp4">
                            </video>
                        </div>
                    </a>
                    <div style="font-weight: 600">@video.Description</div>
                </div>
            }
        </div>
    </div>
</div>

@if (User!.Identity!.IsAuthenticated && User!.Identity!.Name != Model.Username)
{
    <script>
        document.getElementById("follow-button").addEventListener("click", function (event) 
        {
            this.style.display = "none";
            this.nextElementSibling.style.display = "block";
        });

        document.getElementById("unfollow-button").addEventListener("click", function (event) 
        {
            this.style.display = "none";
            this.previousElementSibling.style.display = "block";
        });
    </script>
}

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const videos = document.querySelectorAll('.video-item');

        videos.forEach(video => {
            video.addEventListener('mouseover', function () {
                video.play();
            });

            video.addEventListener('mouseout', function () {
                video.pause();
                video.currentTime = 0;
            });
        });
    });
</script>

Views/User/Upload.cshtml
@model PawPok.Models.Video
@{
    ViewData["Title"] = "Upload";
}

<div class="container">
    <h1 class="text-center" style="margin-bottom: 40px">Upload video</h1>
    <div class="row">
        <div class="mx-auto">
            <form id="account" asp-controller="User" asp-action="Upload" method="post" enctype="multipart/form-data" style="display: flex; flex-direction: row; justify-content: center">
                <div style="margin-right: 40px">
                    <div class="mb-2">Video</div>
                    <input id="video-status" class="form-control" readonly/>
                    <button type="button" class="follow-btn" style="margin:auto; margin-top: 20px" onclick="document.getElementById('browse-file').click()">Browse</button>
                    <input id="browse-file" type="file" name="file" style="display: none" accept=".mp4" onchange="preview_video(event)" />

                    <div class="form-group" style="margin-top: 20px">
                        <label asp-for="Description" class="control-label mb-2">Description</label>
                        <textarea id="desc-area" asp-for="Description" class="form-control mb-2" style="height: 200px; width: 400px; resize: none" spellcheck="false" placeholder="Share more about your video here..." oninput="update_desc_length()"></textarea>
                        <span id="desc-length">0 / 2000</span>
                    </div>

                    @if (ViewData.ModelState[string.Empty] != null)
                    {
                        <div class="error-summary" style="margin-top: 20px">
                            @foreach (var error in ViewData.ModelState[string.Empty]!.Errors)
                            {
                                <div class="error-item text-danger">
                                    @error.ErrorMessage
                                </div>
                            }
                        </div>
                    }

                    <a href="@Url.Action("Index")" class="follow-btn" style="margin-top: 20px; margin-right: 10px">Discard</a>
                    <button type="submit" class="follow-btn" style="margin-top: 20px">Post</button>
                </div>

                <div class="form-group" style="display: flex; justify-content: center">
                    <video width="350" style="border-radius: 12px; border: 1px solid #303030" controls>
                        <source id="video-src" src="@(Url.Content(Model.VideoURL))" type="video/mp4" />
                    </video>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    function update_desc_length() {
        var desc_area = document.getElementById('desc-area');
        var desc_length = document.getElementById('desc-length');

        desc_length.innerText = desc_area.value.length + ' / 2000';

        if (desc_area.value.length > 2000)
            desc_length.style.color = 'var(--bs-danger)';
        else
            desc_length.style.color = '#eee';
    }

    document.addEventListener('DOMContentLoaded', function () {
        update_desc_length();
    });

    function preview_video(event) {
        var input = event.target;
        var filename = input.value.split('\\').pop();
        var source = document.getElementById('video-src');
        var video = source.parentElement;
        var status = document.getElementById('video-status');

        if (!is_valid_extension(filename)) {
            input.value = '';
            source.removeAttribute('src');
            video.load();
            status.value = '';
        }

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                source.src = e.target.result;
                video.load();
                status.value = filename;
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    function is_valid_extension(filename) {
        var extension = filename.split('.').pop().toLowerCase();
        return extension === 'mp4';
    }
</script>